import type { Metadata } from "next";
import { Inter, Roboto_Slab, Roboto_Mono} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
});

const roboto_slab = Roboto_Slab({
  subsets: ['latin'],
  variable: '--font-roboto-slab',
  display: 'swap',
})

const jaro = localFont({ 
  src: './jaro.ttf',
  variable: '--font-jaro',
})

const daddy_time = localFont({ 
  src: './dt.otf',
  variable: '--font-daddytime',
})


export const metadata: Metadata = {
  title: "Marcus Andrist's Site",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={
        `${inter.className} ${roboto_slab.variable} ${roboto_mono.variable}
        ${jaro.variable} ${daddy_time.variable}`}
      >{children}</body>
    </html>
  );
}
